name: trocasweb
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - ipykernel
  - jupyter-book
  # sphinx-design may not be needed after updating to jb 0.13
  - sphinx-design
  - ghp-import
  - pip
  - pandas
  - geopandas
  - mapclassify
  - xarray
  - matplotlib-base
  - seaborn
  - folium
  - cartopy
  - contextily
