name: trocasweb
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - ipykernel
  - jupyter-book
  - ghp-import
  - pip
  # - sphinx
  - pandas
  - geopandas
  - mapclassify
  - xarray
  - matplotlib-base
  - seaborn
  - folium
  - cartopy
  - contextily
